version: '3.8'

services:
  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
    ports:
      - 9000:9000
    command: server /data

  postgres:
    image: postgres:9.6.19
    environment:
      POSTGRES_DB: gateway
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - '9200:9200'
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    build: ./.docker/logstash
    volumes:
      - ./.docker/logstash/postgres-jdbc-input.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./.docker/logstash/product_mapping.json:/usr/share/logstash/product_mapping.json
    environment:
      LOGSTASH_JDBC_URL: jdbc:postgresql://postgres:5432/gateway
      LOGSTASH_JDBC_USERNAME: gateway
      LOGSTASH_JDBC_PASSWORD: gateway
      LOGSTASH_ELASTICSEARCH_HOST: http://elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch

  pg_migrate:
    image: migrate/migrate
    volumes:
    - ./migrations/pg:/migrations/pg
    restart: on-failure
    depends_on:
      - postgres
    command: ["-database", "postgresql://gateway:gateway@postgres:5432/gateway?sslmode=disable", "-path", "/migrations/pg", "up"]

  gateway:
    build: .
    environment:
      S3_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: miniominio
      S3_REGION: us-east-1
      S3_BUCKET_NAME: test
      GC_VISION_PATH_TO_KEYS: /.gcloaud
      ELASTIC_URLS: http://elasticsearch:9200
      GATEWAY_DB: postgresql://gateway:gateway@postgres:5432/gateway?sslmode=disable
    restart: on-failure
    depends_on:
      - s3
      - elasticsearch
      - postgres
    ports:
    - 8081:8080
