version: '3.8'

services:
  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
    ports:
      - 9000:9000
    command: server /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  gateway:
    build: .
    volumes:
      - ./.gcloaud:/.gcloaud
    environment:
      S3_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: miniominio
      S3_REGION: us-east-1
      S3_BUCKET_NAME: test
      GC_VISION_PATH_TO_KEYS: /.gcloaud/SimpleImageParser-e5de18fd004e.json;/.gcloaud/test-items-search-b761860705d4.json
    depends_on:
      - s3
      - elasticsearch
    ports:
    - 8080:8080