name: build-and-push
on: push
jobs:
  build-and-push-job:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: build
        run: make build tag=$BRANCH_NAME
