name: build-and-push
on: push
jobs:
  build-and-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get-branch-name
        uses: nelonoel/branch-name@v1
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: build
        run: echo ${BRANCH_NAME}
